services:
  mc:
    container_name: mc
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    volumes:
    - ./mc-data:/data
    env_file:
      - .env

  web:
    image: nginx:latest
    ports:
      - 80:80
    profiles:
      - test
